version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html/
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/

  php-fpm:
    build: ./php-fpm
    volumes:
      - .:/app
    env_file:
      - php-fpm/php.env

  pgsql:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file:
      - pgsql/pgsql.env
    volumes:
      - ".pgsql/db_dump:/db_dump"
